### ISSUE TITLE
vcpkg integration ?

### ISSUE THREAD

**Issue by heightball** [HeliumProject/Core#15]
would be possible to include your project to vcpkg??
since vcpkg run on windows and linux now, would simplify the integration in program.

https://github.com/Microsoft/vcpkg

**Comment by gorlak** [comment]
This issue should be in vcpkg's tracker. We aren't going to undertake this as a factor of Core. That being said, if someone spearheaded the work I'm happy to help. It wouldn't be hard, all Helium code straight up compiles with no header munging or autoconf.
